sudo: true
language: rust
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

addons:
    apt:
        packages:
            - libssl-dev

branches:
  only:
  - master

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

after_success: |
  sudo ldconfig &&
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    if ! [ -x "$(command -v cargo-tarpaulin)" ]; then bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh); fi &&
    cargo tarpaulin --ignore-tests --out Xml --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
